import React from 'react';
import { Badge, MetricCard, SectionCard, SectionHeader, cleanText, formatNumber, formatPercent } from '../ui/DashboardPrimitives';

function getDriverRows(data) {
  const rows = [
    {
      label: 'Base value',
      value: data?.effectiveCircleRate ? `Circle rate context: INR ${Number(data.effectiveCircleRate).toLocaleString('en-IN')}/sqft` : 'Circle-rate context applied',
      tone: 'slate',
    },
    {
      label: 'Market adjustment',
      value: data?.ipi ? `Infrastructure-price index ${formatNumber(data.ipi, 2)}` : 'Location and demand context applied',
      tone: 'emerald',
    },
    {
      label: 'Property and condition adjustment',
      value: data?.drivers?.length ? data.drivers.map((driver) => `${driver.name} ${driver.impact}`).join(', ') : 'Standard configuration profile',
      tone: 'slate',
    },
    {
      label: 'Legal risk adjustment',
      value: data?.confidenceBreakdown?.legal > 0 ? 'Known legal status supports confidence' : 'Legal evidence may require underwriter review',
      tone: data?.confidenceBreakdown?.legal > 0 ? 'emerald' : 'amber',
    },
    {
      label: 'Liquidity discount',
      value: `Resale liquidity score ${data?.propScore ?? 'Not available'}/100; time to liquidate ${cleanText(data?.timeToSell)}`,
      tone: data?.propScore < 50 ? 'red' : data?.propScore < 75 ? 'amber' : 'emerald',
    },
    {
      label: 'Historical adjustment',
      value: data?.historicalCaseSummary
        ? `${data.historicalCaseSummary.overallSignal || 'Mixed'} signal, confidence impact ${formatNumber(data.historicalCaseSummary.confidenceAdjustment, 3)}`
        : 'Historical layer unavailable',
      tone: data?.historicalCaseSummary?.overallSignal === 'Positive' ? 'emerald' : 'slate',
    },
  ];
  return rows;
}

export default function ValuationLiquiditySection({ data }) {
  if (!data) return null;

  const portfolioSummary = data.portfolioRiskSummary?.portfolioSummary || {};
  const recommendedLtv = portfolioSummary.recommendedLtv
    ? formatPercent(portfolioSummary.recommendedLtv)
    : `${data.ltv ?? 'Not available'}${Number.isFinite(data.ltv) ? '%' : ''}`;

  return (
    <SectionCard>
      <SectionHeader
        icon="monitoring"
        title="Valuation & Liquidity"
        eyebrow="VALUATION_ENGINE"
        description="Deterministic market value, forced-sale recovery, liquidation timeline, and confidence outputs for lender review."
        actions={<Badge tone="slate">Numeric engine only</Badge>}
      />

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-6">
        <MetricCard label="Estimated market value" value={data.marketValue} tone="indigo" icon="payments" />
        <MetricCard label="Distress sale value" value={data.distressValue} tone="amber" icon="trending_down" />
        <MetricCard label="Recommended LTV" value={recommendedLtv} icon="account_balance" />
        <MetricCard label="Time to liquidate" value={data.timeToSell} icon="schedule" />
        <MetricCard label="Confidence score" value={formatNumber(data.confidence, 2)} sublabel="After historical layer" icon="verified" />
        <MetricCard label="Liquidity signal" value={`${data.propScore ?? 'Not available'}/100`} tone={data.propScore < 50 ? 'red' : data.propScore < 75 ? 'amber' : 'emerald'} icon="speed" />
      </div>

      <div className="mt-5 rounded-xl border border-indigo-100 bg-indigo-50/50 p-4">
        <p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Distress value note</p>
        <p className="mt-1 text-sm font-semibold leading-relaxed text-indigo-950">
          Distress value estimates forced-sale recovery after liquidity discount. It is not generated by the LLM.
        </p>
      </div>

      <div className="mt-5">
        <div className="mb-3 flex items-center justify-between gap-3">
          <h4 className="text-sm font-bold text-slate-900">Driver breakdown</h4>
          <Badge tone="slate">Audit-safe factors</Badge>
        </div>
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
          {getDriverRows(data).map((row) => (
            <div key={row.label} className="rounded-xl border border-slate-200 bg-slate-50 p-4">
              <div className="mb-2 flex items-center justify-between gap-3">
                <p className="text-xs font-bold uppercase tracking-wider text-slate-500">{row.label}</p>
                <Badge tone={row.tone}>{row.tone === 'emerald' ? 'Supportive' : row.tone === 'red' ? 'Risk' : row.tone === 'amber' ? 'Review' : 'Applied'}</Badge>
              </div>
              <p className="text-sm font-semibold leading-relaxed text-slate-700">{cleanText(row.value)}</p>
            </div>
          ))}
        </div>
      </div>
    </SectionCard>
  );
}
